<a href="https://colab.research.google.com/github/sulav063/Machine_Learning_Workshop/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

*   Creating single dimesnional arrays ✅
*   Multi dimensional array ✅
*   Randomly generated arrays ✅
*   Element wise opetations ✅
*   Summarizing operations ✅


## Single Dimensional Array

In [1]:
import numpy as np

In [2]:
# Create an array with all the elemests zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
#creating an array with all the  elememts one
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
# create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
np.array([1, 2, 3, 5,5])

array([1, 2, 3, 5, 5])

In [6]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
# create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

## Multidimensional Arrays


In [8]:
#matrix with al elements 0
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# square matrix  with all elemets 1
np.ones([4, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
# square matrix 3 by 3 with elemnts starting from 1 to 9
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# replacing a array
a[0, 1]=20
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [13]:
# last row all 1
a[2] = [1, 1, 1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [14]:
# last column all 2
a[:, 2]= [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [15]:
# 3 by 3 matrix all elements 10
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly Generated Array
- Numpy can create arrays filled with random numbers
- To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values, the sequence of random numbers will be changed.

In [16]:
np.random.rand(5)

array([0.13929842, 0.54128597, 0.25391554, 0.10375365, 0.45862465])

In [17]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [18]:
np.random.randn(5,2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [19]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])

## Elements wise operation on entire arrays element by element

In [20]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
b=(10+(a+2))
b

array([12, 13, 14, 15, 16])

In [22]:
a

array([0, 1, 2, 3, 4])

In [23]:
a= a*5
a

array([ 0,  5, 10, 15, 20])

In [24]:
a>=2

array([False,  True,  True,  True,  True])

In [25]:
a>b

array([False, False, False, False,  True])

In [26]:
# summarization of thr data
# Numpy provides function for sumarizing array data
a.std()

7.0710678118654755

In [27]:
a.min()

0

In [28]:
a.max()

20

In [29]:
a.sum()

50